#!/bin/sh
# Auto-generated by py_self_executable — do not edit.
set -e
_SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
_HASH="__HASH__"
_MAIN="__MAIN__"
_OFFSET=__OFFSET__
_CACHE="${HOME:-/tmp}/.cache/py_exe/${_HASH}"
if [ ! -f "${_CACHE}/.done" ]; then
    rm -rf "${_CACHE}.tmp" 2>/dev/null || true
    mkdir -p "${_CACHE}.tmp"
    tail -c +$(expr "${_OFFSET}" + 1) "${_SELF}" | tar xzf - -C "${_CACHE}.tmp"
    touch "${_CACHE}.tmp/.done"
    mv "${_CACHE}.tmp" "${_CACHE}"
fi
exec "${_CACHE}/python/bin/python3" "${_CACHE}/app/${_MAIN}" "$@"
exit 0
