FROM grafana/grafana:11.1.0
COPY grafana/provisioning /etc/grafana/provisioning
COPY grafana/dashboards   /var/lib/grafana/dashboards
ENV GF_SECURITY_ADMIN_USER=admin \
    GF_SECURITY_ADMIN_PASSWORD=admin \
    GF_USERS_ALLOW_SIGN_UP=false \
    GF_AUTH_ANONYMOUS_ENABLED=true \
    GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
